# Generated by Django 5.2.6 on 2026-08-23 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasets', '0001_initial'),
        ('geo', '0002_departement_population_departement_superficie_km2'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopulationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('region', 'Région'), ('departement', 'Département')], max_length=20)),
                ('annee', models.PositiveIntegerField()),
                ('population', models.PositiveIntegerField()),
                ('hommes', models.PositiveIntegerField(blank=True, null=True)),
                ('femmes', models.PositiveIntegerField(blank=True, null=True)),
                ('value_type', models.CharField(choices=[('officielle', 'Officielle'), ('estimee', 'Estimée')], default='officielle', max_length=12)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('departement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='population_records', to='geo.departement')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='population_records', to='geo.region')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='population_records', to='datasets.datasource')),
            ],
            options={
                'ordering': ['-annee'],
                'indexes': [models.Index(fields=['entity_type', 'annee'], name='demographie_entity__49bd48_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(models.Q(('departement__isnull', True), ('entity_type', 'region'), ('region__isnull', False)), models.Q(('departement__isnull', False), ('entity_type', 'departement'), ('region__isnull', False)), _connector='OR'), fields=('entity_type', 'region', 'departement', 'annee'), name='uniq_population_entite_annee')],
            },
        ),
    ]
