# Generated by Django 5.2.6 on 2026-08-23 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasets', '0001_initial'),
        ('demographie', '0001_initial'),
        ('geo', '0002_departement_population_departement_superficie_km2'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='populationrecord',
            name='uniq_population_entite_annee',
        ),
        migrations.AddConstraint(
            model_name='populationrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('departement__isnull', True), ('entity_type', 'region'), ('region__isnull', False)), fields=('region', 'annee'), name='uniq_population_region_annee'),
        ),
        migrations.AddConstraint(
            model_name='populationrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('departement__isnull', False), ('entity_type', 'departement'), ('region__isnull', False)), fields=('departement', 'annee'), name='uniq_population_departement_annee'),
        ),
    ]
