[pytest]
DJANGO_SETTINGS_MODULE = GalsenifyDj.settings
python_files = test_*.py tests.py tests_*.py
addopts = -p no:cacheprovider
filterwarnings =
    ignore::DeprecationWarning:drf_yasg
    ignore::DeprecationWarning:rest_framework
