# Generated by Django 5.2.6 on 2026-08-23 03:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationClimatique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.CharField(max_length=20, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('altitude', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['nom'],
                'indexes': [models.Index(fields=['nom'], name='climat_stat_nom_48e81a_idx')],
            },
        ),
        migrations.CreateModel(
            name='ObservationMensuelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.PositiveIntegerField()),
                ('mois', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('tavg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('tmin', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('tmax', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('prcp_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('nb_jours', models.PositiveIntegerField(default=0)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observations_climat', to='datasets.datasource')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='climat.stationclimatique')),
            ],
            options={
                'ordering': ['-annee', '-mois'],
                'indexes': [models.Index(fields=['station', 'annee'], name='climat_obse_station_3b8954_idx')],
                'constraints': [models.UniqueConstraint(fields=('station', 'annee', 'mois'), name='uniq_observation_station_annee_mois')],
            },
        ),
    ]
