# Generated by Django 4.2 on 2023-04-16 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('population', models.PositiveIntegerField()),
                ('superficie', models.PositiveIntegerField()),
                ('arrondissements', models.JSONField()),
            ],
            options={
                'verbose_name': 'Departement',
                'verbose_name_plural': 'Departements',
            },
        ),
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pays', models.CharField(max_length=255)),
                ('capital', models.CharField(max_length=255)),
                ('langueOfficielle', models.CharField(max_length=255)),
                ('languesNationales', models.JSONField()),
                ('monnaie', models.CharField(max_length=255)),
                ('devise', models.CharField(max_length=255)),
                ('drapeau', models.URLField(max_length=255)),
                ('codeIso', models.CharField(max_length=255)),
                ('indicatif', models.PositiveIntegerField()),
                ('habitants', models.PositiveIntegerField()),
                ('surface', models.PositiveIntegerField()),
                ('regions', models.PositiveIntegerField()),
                ('departments', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Pays',
                'verbose_name_plural': 'Pays',
            },
        ),
        migrations.CreateModel(
            name='Regions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('population', models.PositiveIntegerField()),
                ('superficie', models.PositiveIntegerField()),
                ('departments', models.JSONField()),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Regions',
            },
        ),
    ]
