# Generated by Django 4.2 on 2025-02-05 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_arrondissement_commune'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrondissement',
            name='nom',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='arrondissement',
            name='region',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='commune',
            name='nom',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='commune',
            name='region',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='departements',
            name='nom',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='departements',
            name='region',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='regions',
            name='code',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='regions',
            name='nom',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='village',
            name='nom',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='village',
            name='region',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='arrondissement',
            index=models.Index(fields=['nom', 'region'], name='app_arrondi_nom_284d81_idx'),
        ),
        migrations.AddIndex(
            model_name='commune',
            index=models.Index(fields=['nom', 'region'], name='app_commune_nom_fc23fc_idx'),
        ),
        migrations.AddIndex(
            model_name='departements',
            index=models.Index(fields=['nom', 'region'], name='app_departe_nom_845f96_idx'),
        ),
        migrations.AddIndex(
            model_name='pays',
            index=models.Index(fields=['pays'], name='app_pays_pays_54fce5_idx'),
        ),
        migrations.AddIndex(
            model_name='pays',
            index=models.Index(fields=['capital'], name='app_pays_capital_f750dc_idx'),
        ),
        migrations.AddIndex(
            model_name='regions',
            index=models.Index(fields=['nom', 'code'], name='app_regions_nom_ec09bf_idx'),
        ),
        migrations.AddIndex(
            model_name='village',
            index=models.Index(fields=['nom', 'region'], name='app_village_nom_ba5ef5_idx'),
        ),
    ]
