# Generated by Django 4.2 on 2025-02-05 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_arrondissement_nom_alter_arrondissement_region_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='arrondissement',
            name='app_arrondi_nom_284d81_idx',
        ),
        migrations.RemoveIndex(
            model_name='commune',
            name='app_commune_nom_fc23fc_idx',
        ),
        migrations.RemoveIndex(
            model_name='departements',
            name='app_departe_nom_845f96_idx',
        ),
        migrations.RemoveIndex(
            model_name='pays',
            name='app_pays_pays_54fce5_idx',
        ),
        migrations.RemoveIndex(
            model_name='pays',
            name='app_pays_capital_f750dc_idx',
        ),
        migrations.RemoveIndex(
            model_name='regions',
            name='app_regions_nom_ec09bf_idx',
        ),
        migrations.RemoveIndex(
            model_name='village',
            name='app_village_nom_ba5ef5_idx',
        ),
        migrations.AlterField(
            model_name='arrondissement',
            name='nom',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='arrondissement',
            name='region',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='commune',
            name='nom',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='commune',
            name='region',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='departements',
            name='nom',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='departements',
            name='region',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='regions',
            name='code',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='regions',
            name='nom',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='village',
            name='nom',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='village',
            name='region',
            field=models.CharField(max_length=255),
        ),
    ]
