# Generated by Django 4.2 on 2025-02-26 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_universites'),
    ]

    operations = [
        migrations.RenameField(
            model_name='universites',
            old_name='region',
            new_name='logo',
        ),
    ]
