# Generated by Django 5.2.6 on 2026-08-23 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Culture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_faostat', models.CharField(max_length=20, unique=True)),
                ('nom', models.CharField(max_length=250)),
            ],
            options={
                'ordering': ['nom'],
                'indexes': [models.Index(fields=['nom'], name='agriculture_nom_d1d086_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductionAgricole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.PositiveIntegerField()),
                ('element', models.CharField(choices=[('production_tonnes', 'Production (tonnes)'), ('superficie_recoltee_ha', 'Superficie récoltée (ha)'), ('rendement_hg_ha', 'Rendement (hg/ha)')], max_length=30)),
                ('valeur', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True)),
                ('flag', models.CharField(blank=True, default='', max_length=3)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('culture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productions', to='agriculture.culture')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productions_agricoles', to='datasets.datasource')),
            ],
            options={
                'ordering': ['-annee', 'culture__nom'],
                'indexes': [models.Index(fields=['annee'], name='agriculture_annee_23fe14_idx')],
                'constraints': [models.UniqueConstraint(fields=('culture', 'annee', 'element'), name='uniq_production_culture_annee_element')],
            },
        ),
    ]
