# Generated by Django 5.2.6 on 2026-08-23 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicateurEconomique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('nom', models.CharField(max_length=250)),
                ('nom_officiel', models.CharField(blank=True, default='', max_length=250)),
                ('categorie', models.CharField(choices=[('pib', 'PIB'), ('prix', 'Prix & inflation'), ('commerce', 'Commerce'), ('emploi', 'Emploi'), ('dette', 'Dette & finance publique'), ('secteurs', 'Structure économique')], max_length=20)),
                ('unite', models.CharField(blank=True, default='', max_length=30)),
                ('decimal', models.CharField(blank=True, default='', max_length=3)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicateurs_economiques', to='datasets.datasource')),
            ],
            options={
                'ordering': ['categorie', 'code'],
            },
        ),
        migrations.CreateModel(
            name='ObservationEconomique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.PositiveIntegerField()),
                ('valeur', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('indicateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='economie.indicateureconomique')),
            ],
            options={
                'ordering': ['-annee'],
            },
        ),
        migrations.AddIndex(
            model_name='indicateureconomique',
            index=models.Index(fields=['categorie'], name='economie_in_categor_03e3e2_idx'),
        ),
        migrations.AddIndex(
            model_name='observationeconomique',
            index=models.Index(fields=['annee'], name='economie_ob_annee_b18e00_idx'),
        ),
        migrations.AddConstraint(
            model_name='observationeconomique',
            constraint=models.UniqueConstraint(fields=('indicateur', 'annee'), name='uniq_observation_indicateur_annee'),
        ),
    ]
