# Generated by Django 5.2.6 on 2026-08-22 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arrondissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geometry', models.JSONField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('pcode', models.CharField(max_length=20, unique=True)),
                ('nom', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geometry', models.JSONField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('pcode', models.CharField(max_length=20, unique=True)),
                ('nom', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geometry', models.JSONField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('nom', models.CharField(max_length=150)),
                ('type', models.CharField(choices=[('commune', 'Commune'), ('communaute_rurale', 'Communauté rurale'), ('autre', 'Autre')], default='commune', max_length=20)),
                ('population', models.PositiveIntegerField(blank=True, null=True)),
                ('arrondissement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communes', to='geo.arrondissement')),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='communes', to='geo.departement')),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='arrondissement',
            name='departement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arrondissements', to='geo.departement'),
        ),
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='Sénégal', max_length=100)),
                ('code_iso2', models.CharField(default='SN', max_length=2, unique=True)),
                ('capitale', models.CharField(blank=True, default='', max_length=100)),
                ('indicatif', models.PositiveIntegerField(blank=True, null=True)),
                ('monnaie', models.CharField(blank=True, default='', max_length=50)),
                ('devise', models.CharField(blank=True, default='', max_length=150)),
                ('population', models.PositiveIntegerField(blank=True, null=True)),
                ('superficie_km2', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
            ],
            options={
                'ordering': ['nom'],
                'indexes': [models.Index(fields=['nom'], name='geo_pays_nom_9e62ec_idx')],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geometry', models.JSONField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('pcode', models.CharField(max_length=20, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('code_court', models.CharField(blank=True, max_length=10, null=True)),
                ('chef_lieu', models.CharField(blank=True, max_length=100, null=True)),
                ('population', models.PositiveIntegerField(blank=True, null=True)),
                ('superficie_km2', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('pays', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='regions', to='geo.pays')),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='departement',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departements', to='geo.region'),
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geometry', models.JSONField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('nom', models.CharField(max_length=200)),
                ('population', models.PositiveIntegerField(blank=True, null=True)),
                ('commune', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='villages', to='geo.commune')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='villages', to='geo.region')),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.AddIndex(
            model_name='commune',
            index=models.Index(fields=['nom'], name='geo_commune_nom_a8081d_idx'),
        ),
        migrations.AddConstraint(
            model_name='commune',
            constraint=models.UniqueConstraint(fields=('departement', 'nom'), name='uniq_commune_departement_nom'),
        ),
        migrations.AddIndex(
            model_name='arrondissement',
            index=models.Index(fields=['nom'], name='geo_arrondi_nom_42f71c_idx'),
        ),
        migrations.AddConstraint(
            model_name='arrondissement',
            constraint=models.UniqueConstraint(fields=('departement', 'nom'), name='uniq_arrondissement_departement_nom'),
        ),
        migrations.AddIndex(
            model_name='region',
            index=models.Index(fields=['nom'], name='geo_region_nom_560ac5_idx'),
        ),
        migrations.AddIndex(
            model_name='departement',
            index=models.Index(fields=['nom'], name='geo_departe_nom_7791dd_idx'),
        ),
        migrations.AddConstraint(
            model_name='departement',
            constraint=models.UniqueConstraint(fields=('region', 'nom'), name='uniq_departement_region_nom'),
        ),
        migrations.AddIndex(
            model_name='village',
            index=models.Index(fields=['nom'], name='geo_village_nom_134be3_idx'),
        ),
        migrations.AddConstraint(
            model_name='village',
            constraint=models.UniqueConstraint(fields=('region', 'nom'), name='uniq_village_region_nom'),
        ),
    ]
